POST /internal/echo HTTP/1.1
Host: localhost:8000
Content-Type: application/ld+json
Accept: text/turtle; version=2.2.0

{
    "@context": {
        "cargo": "https://onerecord.iata.org/ns/cargo#"
    },
    "@type": "cargo:Piece",
    "cargo:coload": {
        "@type": "http://www.w3.org/2001/XMLSchema#boolean",
        "@value": "false"
    },
    "cargo:specialHandlingCodes": [
        {
            "@id": "https://onerecord.iata.org/ns/code-lists/SpecialHandlingCode#VAL"
        }
    ]
}


###

GET / HTTP/1.1
Host: localhost:8000
Content-Type: application/ld+json; version=2.2.0
Accept: application/ld+json; version=2.2.0

###

GET /subscriptions?topicType=https://onerecord.iata.org/ns/api%23LOGISTICS_OBJECT_IDENTIFIER&topic=https://1r.example.com/logistics-objects/1a8ded38-1804-467c-a369-81a411416b7c HTTP/1.1
Host: localhost:8000
Accept: application/ld+json; version=2.2.0

###

POST /notifications HTTP/1.1
Host: localhost:8000
Content-Type: application/ld+json; version=2.2.0
Accept: application/ld+json; version=2.2.0

{
    "@context": {
        "api": "https://onerecord.iata.org/ns/api#"
    },
    "@type": "api:Notification",
    "api:hasEventType": {
        "@id": "api:LOGISTICS_OBJECT_CREATED"
    },
    "api:hasLogisticsObject": {
        "@id": "https://1r.example.com/logistics-objects/1a8ded38-1804-467c-a369-81a411416b7c"
    },
    "api:hasLogisticsObjectType": {
        "@type": "http://www.w3.org/2001/XMLSchema#anyURI",
        "@value": "https://onerecord.iata.org/ns/cargo#Piece"
    },
    "api:isTriggeredBy": {
        "@id": "https://1r.example.com/action-requests/599fea49-7287-42af-b441-1fa618d2aaed"
    },
    "api:hasChangedProperty": [
        {
            "@id": "https://onerecord.iata.org/ns/cargo#coload"
        },
        {
            "@id": "https://onerecord.iata.org/ns/cargo#specialHandlingCodes"
        }
    ]
}

###

POST /logistics-objects HTTP/1.1
Host: localhost:8000
Content-Type: application/ld+json; version=2.2.0
Accept: application/ld+json; version=2.2.0

{
    "@context": {
        "cargo": "https://onerecord.iata.org/ns/cargo#"
    },
    "@type": "cargo:Piece",
    "cargo:coload": {
        "@type": "http://www.w3.org/2001/XMLSchema#boolean",
        "@value": "false"
    },
    "cargo:specialHandlingCodes": [
        {
            "@id": "https://onerecord.iata.org/ns/code-lists/SpecialHandlingCode#VAL"
        }
    ]
}

###

POST /logistics-objects HTTP/1.1
Host: localhost:8000
Content-Type: application/ld+json; version=2.2.0
Accept: application/ld+json; version=2.2.0

{
    "@context": {
        "cargo": "https://onerecord.iata.org/ns/cargo#"
    },
    "@type": "cargo:Shipment",
    "cargo:goodsDescription": "Lots of awesome ONE Record information materials",
    "cargo:pieces": [
        {
            "@id": "https://1r.example.com/logistics-objects/1a8ded38-1804-467c-a369-81a411416b7c"
        }
    ]
}

###

POST /internal/assessment HTTP/1.1
Host: localhost:8000

{
    "target": "http://localhost:8000/logistics-objects/1a8ded38-1804-467c-a369-81a411416b7c",
    "status": "RFI"
}

###

POST /logistics-objects/1a8ded38-1804-467c-a369-81a411416b3c/logistics-events HTTP/1.1
Host: localhost:8000
Content-Type: application/ld+json; version=2.2.0
Accept: application/ld+json; version=2.2.0

{
    "@context": {
        "cargo": "https://onerecord.iata.org/ns/cargo#"
    },
    "@type": "cargo:LogisticsEvent",
    "cargo:creationDate": {
        "@type": "http://www.w3.org/2001/XMLSchema#dateTime",
        "@value": "2023-04-01T10:38:01.000Z"
    },
    "cargo:eventDate": {
        "@type": "http://www.w3.org/2001/XMLSchema#dateTime",
        "@value": "2023-04-01T10:38:01.000Z"
    },
    "cargo:eventCode": {
        "@id": "https://onerecord.iata.org/ns/code-lists/StatusCode#DEP"
    },
    "cargo:eventName": "Consignment departed on a specific flight",
    "cargo:eventTimeType": {
        "@id": "cargo:ACTUAL",
        "@type": "cargo:EventTimeType"
    },
    "cargo:partialEventIndicator": false,
    "cargo:eventFor": {
        "@type": "cargo:Shipment",
        "@id": "https://1r.example.com/logistics-objects/1a8ded38-1804-467c-a369-81a411416b3c"
    },
    "cargo:recordingOrganization": {
        "@type": "cargo:Company",
        "@id": "https://1r.example.com/logistics-objects/957e2622-9d31-493b-8b8f-3c805064dbda"
    }
}
